apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plexus.name" . }}
  namespace: {{ include "plexus.namespace" . }}
  labels:
    {{- include "plexus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "plexus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plexus.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "plexus.name" . }}
      containers:
      - name: controller
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        {{- if .Values.leaderElection }}
        - --leader-elect
        {{- end }}
        {{- if .Values.clusterSecretNamespace }}
        - --cluster-secret-namespace={{ .Values.clusterSecretNamespace }}
        {{- end }}
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: health
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
